# DataFrame sort agg groupby

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [2]:
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 1. DataFrame 정렬(sort)

### (1) sort_values()
- DataFrame을 특정 컬럼 기준으로 정렬할 때 사용
- 문법

  DF.sort_values(by='컬럼', ascending=True)
  - ascending=T 오름차순
  - ascending=F 내림차순

In [3]:
td_sort_name = titanic_df.sort_values(by= 'Name')
td_sort_name.reset_index(inplace=True)
td_sort_name.drop(columns='index', axis=1, inplace=True)
td_sort_name.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
1,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
2,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S
3,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.00,NaN,C
4,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.00,NaN,C

In [4]:
td_sort_pclass = titanic_df.sort_values(by='Pclass', ascending=False)
td_sort_pclass.reset_index(drop=True, inplace=True) # drop=True 기존 인덱스는 삭제
td_sort_pclass.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,512,0,3,"Webber, Mr. James",male,NaN,0,0,SOTON/OQ 3101316,8.0500,NaN,S
2,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S
3,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
4,503,0,3,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q

In [5]:
titanic_df.sort_values(by=['Name', 'Pclass']).head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S

## 2. 집계 함수(Aggregation)

### (1) count()
- 결측치 제외
- 실제 데이터 갯수 반환

In [6]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

### (2) shape
- 전체 데이터 수를 확인하는 작업에서는 count() 함수보다 shape을 사용하는 것이 유리

In [7]:
titanic_df.shape

(891, 12)

### (3) mean()
- 평균

In [8]:
titanic_df['Age'].mean()

np.float64(29.69911764705882)

In [9]:
print(titanic_df['Fare'].mean().round())

32.0

### (4) sum()
- 합계 집계 함수

In [11]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
titanic_df[['Age', 'Fare']].sum().round(2)

Age     21205.17
Fare    28693.95
dtype: float64

### (5) min()/ max()
- 최소/최대값 집계 함수

In [17]:
print(titanic_df[['Age', 'Fare']].min())
print('-'*40)
print(titanic_df[['Age', 'Fare']].max())

Age     0.42
Fare    0.00
dtype: float64
----------------------------------------
Age      80.0000
Fare    512.3292
dtype: float64

## 3. Group By
- 특정 컬럼 기준으로 데이터를 그룹화할 때 사용
- 문법
  DF.GroupBy('컬럼리스트')

In [21]:
# 객실 등급별 이원수 조회
titanic_df.groupby('Pclass').count()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

In [23]:
titanic_df.groupby('Embarked').count()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Embarked,,,,,,,,,,,
C,168,168,168,168,168,130,168,168,168,168,69
Q,77,77,77,77,77,28,77,77,77,77,4
S,644,644,644,644,644,554,644,644,644,644,129

## 4. agg()
- 집계 함수
- 그룹별 서로 다른 집계 함수 적용

In [24]:
titanic_df.agg(
    {
        'Pclass' : 'count',
        'Fare' : 'sum'
    }
)

Pclass      891.0000
Fare      28693.9493
dtype: float64

In [25]:
titanic_df.groupby('Embarked').agg(
    {
        'Pclass' : 'count',
        'Fare' : 'sum'
    }
)

          Pclass        Fare
Embarked
C            168  10072.2962
Q             77   1022.2543
S            644  17439.3988

In [28]:
# 객실 등급별 그룹, age 최대 fare 평균
titanic_df.groupby('Pclass').agg(
    {
        'Age':'max',
        'Fare':'mean'
    }
)

         Age       Fare
Pclass
1       80.0  84.154687
2       70.0  20.662183
3       74.0  13.675550

In [34]:
# 여러 컬럼에 agg() 함수 적용
titanic_df[['Age', 'Fare']].agg('max')

Age      80.0000
Fare    512.3292
dtype: float64

In [35]:
titanic_df.agg(
    {
        'Age': 'mean',
        'Fare': 'sum',
        'Pclass': 'count',
    }
)

Age          29.699118
Fare      28693.949300
Pclass      891.000000
dtype: float64